import { useEffect, useState } from "react";
import { MaterialIcon } from "../shared/MaterialIcon";
import { usePet } from "../../contexts/PetContext";
import { useMedical } from "../../contexts/MedicalContext";
import { useAuth } from "../../contexts/AuthContext";
import { Appointment } from "../../types/medical";

interface AddAppointmentModalProps {
    isOpen: boolean;
    onClose: () => void;
    initialValues?: Partial<Appointment>;
    sourceEventId?: string;
    onCreated?: (appointment: Appointment) => Promise<void> | void;
    readOnly?: boolean;
}

export function AddAppointmentModal({ isOpen, onClose, initialValues, sourceEventId, onCreated, readOnly = false }: AddAppointmentModalProps) {
    const { activePet, canEditPet } = usePet();
    const { user } = useAuth();
    const { addAppointment } = useMedical();
    const canEditActivePet = canEditPet(activePet);
    const isReadOnly = readOnly || !canEditActivePet;

    const [type, setType] = useState<Appointment["type"]>("checkup");
    const [title, setTitle] = useState("");
    const [date, setDate] = useState("");
    const [time, setTime] = useState("");
    const [veterinarian, setVeterinarian] = useState("");
    const [clinic, setClinic] = useState("");
    const [notes, setNotes] = useState("");
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [submitError, setSubmitError] = useState("");

    useEffect(() => {
        if (!isOpen) return;
        setType(initialValues?.type || "checkup");
        setTitle(initialValues?.title || "");
        setDate(initialValues?.date || "");
        setTime(initialValues?.time || "");
        setVeterinarian(initialValues?.veterinarian || "");
        setClinic(initialValues?.clinic || "");
        setNotes(initialValues?.notes || "");
        setSubmitError("");
    }, [isOpen, initialValues]);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setSubmitError("");
        if (isReadOnly) return;
        if (!activePet) {
            setSubmitError("No hay mascota activa seleccionada.");
            return;
        }
        if (!user?.uid) {
            setSubmitError("Tu sesión no está lista. Cerrá y abrí sesión nuevamente.");
            return;
        }

        setIsSubmitting(true);
        try {
            const newAppointment: Appointment = {
                id: `apt_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
                petId: activePet.id,
                userId: user?.uid,
                petName: activePet.name,
                sourceEventId: sourceEventId || initialValues?.sourceEventId,
                sourceSuggestionKey: initialValues?.sourceSuggestionKey,
                autoGenerated: false,
                type,
                title,
                date,
                time,
                veterinarian: veterinarian || null,
                clinic: clinic || null,
                status: "upcoming",
                notes: notes || undefined,
                createdAt: new Date().toISOString(),
            };

            await addAppointment(newAppointment);
            await onCreated?.(newAppointment);

            onClose();
            // Reset form
            setTitle("");
            setDate("");
            setTime("");
            setVeterinarian("");
            setClinic("");
            setNotes("");
        } catch (error) {
            console.error("Error adding appointment:", error);
            setSubmitError("No se pudo guardar la cita. Revisá los campos e intentá nuevamente.");
        } finally {
            setIsSubmitting(false);
        }
    };

    const typeOptions: { id: Appointment["type"]; label: string; icon: string; color: string }[] = [
        { id: "checkup", label: "Control", icon: "medical_services", color: "bg-emerald-500" },
        { id: "vaccine", label: "Vacuna", icon: "vaccines", color: "bg-emerald-500" },
        { id: "surgery", label: "Cirugía", icon: "healing", color: "bg-red-500" },
        { id: "emergency", label: "Urgencia", icon: "emergency", color: "bg-orange-500" },
        { id: "other", label: "Otro", icon: "more_horiz", color: "bg-slate-500" },
    ];

    if (!isOpen) return null;

    return (
        <>
            {/* Backdrop */}
            <div
                onClick={onClose}
                className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[60] animate-fadeIn"
            />

            {/* Bottom Sheet */}
            <div
                className="fixed inset-x-0 bottom-0 z-[70] bg-white dark:bg-slate-900 rounded-t-3xl shadow-2xl max-h-[90vh] overflow-hidden flex flex-col animate-slideUp"
            >
                        {/* Handle */}
                        <div className="flex justify-center pt-3 pb-2">
                            <div className="w-12 h-1.5 bg-slate-300 dark:bg-slate-700 rounded-full" />
                        </div>

                        <div className="p-6 overflow-y-auto">
                            <div className="flex items-center justify-between mb-6">
                                <h2 className="text-2xl font-black text-slate-900 dark:text-white">Agendar Cita</h2>
                                <button
                                    onClick={onClose}
                                    className="size-10 rounded-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors"
                                >
                                    <MaterialIcon name="close" className="text-xl" />
                                </button>
                            </div>

                            <form onSubmit={handleSubmit} className="space-y-4 pb-4">
                                {isReadOnly && (
                                    <div className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3">
                                        <p className="text-sm font-bold text-slate-700">Acceso de guardián temporal</p>
                                        <p className="mt-1 text-xs text-slate-500">Podés ver la agenda de la mascota, pero no crear ni editar citas.</p>
                                    </div>
                                )}
                                {/* Type Selection */}
                                <div>
                                    <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-3">Tipo de Cita</label>
                                    <div className="flex flex-wrap gap-2">
                                        {typeOptions.map((opt) => (
                                            <button
                                                key={opt.id}
                                                type="button"
                                                onClick={() => setType(opt.id)}
                                                disabled={isReadOnly}
                                                className={`px-4 py-2.5 rounded-xl border-2 transition-all flex items-center gap-2 ${type === opt.id
                                                        ? "border-[#074738] bg-[#074738]/5 text-[#074738] font-bold"
                                                        : "border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-800/50 text-slate-500"
                                                    } ${isReadOnly ? "opacity-60 cursor-not-allowed" : ""}`}
                                            >
                                                <MaterialIcon name={opt.icon} className="text-xl" />
                                                <span className="text-sm">{opt.label}</span>
                                            </button>
                                        ))}
                                    </div>
                                </div>

                                {/* Title */}
                                <div>
                                    <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2">Motivo / Título</label>
                                    <input
                                        type="text"
                                        value={title}
                                        onChange={(e) => setTitle(e.target.value)}
                                        disabled={isReadOnly}
                                        placeholder="Ej: Control anual, Vacuna rabia..."
                                        className="w-full px-4 py-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white focus:ring-2 focus:ring-[#074738] outline-none"
                                        required
                                    />
                                </div>

                                {/* Date & Time */}
                                <div className="grid grid-cols-2 gap-4">
                                    <div>
                                        <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2">Fecha</label>
                                        <input
                                            type="date"
                                            value={date}
                                            onChange={(e) => setDate(e.target.value)}
                                            disabled={isReadOnly}
                                            className="w-full px-4 py-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white focus:ring-2 focus:ring-[#074738] outline-none"
                                            required
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2">Hora</label>
                                        <input
                                            type="time"
                                            value={time}
                                            onChange={(e) => setTime(e.target.value)}
                                            disabled={isReadOnly}
                                            className="w-full px-4 py-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white focus:ring-2 focus:ring-[#074738] outline-none"
                                            required
                                        />
                                    </div>
                                </div>

                                {/* Veterinarian & Clinic */}
                                <div className="grid grid-cols-2 gap-4">
                                    <div>
                                        <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2">Veterinario</label>
                                    <input
                                        type="text"
                                        value={veterinarian}
                                        onChange={(e) => setVeterinarian(e.target.value)}
                                        disabled={isReadOnly}
                                        placeholder="Ej: Dra. Pérez"
                                        className="w-full px-4 py-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white focus:ring-2 focus:ring-[#074738] outline-none"
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2">Clínica</label>
                                    <input
                                        type="text"
                                        value={clinic}
                                        onChange={(e) => setClinic(e.target.value)}
                                        disabled={isReadOnly}
                                        placeholder="Ej: Clínica Veterinaria Central"
                                        className="w-full px-4 py-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white focus:ring-2 focus:ring-[#074738] outline-none"
                                    />
                                </div>
                                </div>

                                {/* Notes */}
                                <div>
                                    <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-2">Notas adicionales</label>
                                    <textarea
                                        value={notes}
                                        onChange={(e) => setNotes(e.target.value)}
                                        disabled={isReadOnly}
                                        placeholder="Llevar estudios previos, en ayunas, etc..."
                                        rows={3}
                                        className="w-full px-4 py-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white focus:ring-2 focus:ring-[#074738] outline-none resize-none"
                                    />
                                </div>

                                {/* Submit */}
                                {submitError && (
                                    <p className="text-sm font-semibold text-red-600 dark:text-red-400">
                                        {submitError}
                                    </p>
                                )}
                                <button
                                    type="submit"
                                    disabled={isSubmitting || isReadOnly}
                                    className="w-full py-4 rounded-xl bg-[#074738] text-white font-bold text-lg shadow-lg shadow-[#074738]/30 hover:bg-[#1a9b7d] active:scale-[0.98] transition-all disabled:opacity-50"
                                >
                                    {isReadOnly ? "Solo lectura" : isSubmitting ? "Agendando..." : "Confirmar Cita"}
                                </button>
                            </form>
                        </div>
                    </div>
        </>
    );
}
