// ============================================================================
// PESSY - Medical Data Types
// Estructura completa para eventos médicos extraídos por el motor de analisis
// ============================================================================

export type DocumentType =
  | "vaccine"
  | "lab_test"
  | "xray"
  | "echocardiogram"
  | "electrocardiogram"
  | "surgery"
  | "medication"
  | "checkup"
  | "other";

export type EventStatus = "processing" | "completed" | "pending";

export type ExtractionConfidence = "high" | "medium" | "low" | "not_detected";

// ============================================================================
// Datos extraídos por el motor de analisis
// ============================================================================
export interface ExtractedData {
  // Clasificación automática
  documentType: DocumentType;
  documentTypeConfidence: ExtractionConfidence;

  // Fecha del estudio/evento
  eventDate: string | null; // ISO 8601
  eventDateConfidence: ExtractionConfidence;

  // Profesional/Clínica
  provider: string | null;
  providerConfidence: ExtractionConfidence;

  // Diagnóstico literal extraído
  diagnosis: string | null;
  diagnosisConfidence: ExtractionConfidence;

  // Observaciones médicas
  observations: string | null;
  observationsConfidence: ExtractionConfidence;

  // Medicación indicada
  medications: MedicationExtracted[];

  // Próxima fecha recomendada (para pendientes)
  nextAppointmentDate: string | null; // ISO 8601
  nextAppointmentReason: string | null;
  nextAppointmentConfidence: ExtractionConfidence;
  suggestedTitle: string | null;

  // Resumen clínico generado automaticamente (lenguaje simple)
  aiGeneratedSummary: string | null;

  // Valores extraídos (para labs, ECG, etc)
  measurements: Measurement[];
}

export interface MedicationExtracted {
  name: string;
  dosage: string | null;
  frequency: string | null;
  duration: string | null;
  confidence: ExtractionConfidence;
}

export interface Measurement {
  name: string; // e.g., "Frecuencia cardíaca", "Peso", "Temperatura"
  value: string;
  unit: string | null;
  referenceRange: string | null;
  confidence: ExtractionConfidence;
}

// ============================================================================
// Evento médico completo
// ============================================================================
export interface MedicalEvent {
  id: string;
  petId: string;
  userId?: string;
  title: string;
  // Archivo original
  documentUrl: string; // URL del Storage (Supabase o local)
  documentPreviewUrl: string | null; // Thumbnail generado
  fileName: string;
  fileType: "image" | "pdf";

  // Estado del procesamiento
  status: EventStatus;

  // Datos extraídos automaticamente
  extractedData: ExtractedData;

  // Metadatos
  ocrProcessed: boolean;
  aiProcessed: boolean;
  fileHash?: string;
  dedupKey?: string;
  createdAt: string; // ISO 8601
  updatedAt: string; // ISO 8601

  // Correlación futura con otros eventos
  relatedEventIds: string[];
  aiSuggestedRelation: string | null; // e.g., "Relacionado con estudio del 18 Nov 2024"
  treatmentNotes?: TreatmentNote[];
}

export interface TreatmentNote {
  id: string;
  text: string;
  interpretedAs: "dose_change" | "interruption" | "positive_progress" | "adverse_effect" | "general_note";
  createdAt: string;
}

// ============================================================================
// Pendiente generado automáticamente
// ============================================================================
export interface PendingAction {
  id: string;
  petId: string;
  userId?: string;

  // Tipo de acción
  type: "vaccine_due" | "checkup_due" | "medication_refill" | "test_pending" | "follow_up";

  // Información visible
  title: string;
  subtitle: string;

  // Fechas
  dueDate: string; // ISO 8601
  createdAt: string;

  // Origen
  generatedFromEventId: string | null; // Link al evento que lo generó
  autoGenerated: boolean; // true si fue creado automaticamente

  // Estado
  completed: boolean;
  completedAt: string | null;

  // Notificaciones
  reminderEnabled: boolean;
  reminderDaysBefore: number; // Días antes de dueDate para recordar
}

// ============================================================================
// Medicación activa
// ============================================================================
export interface ActiveMedication {
  id: string;
  petId: string;
  userId?: string;

  // Información del medicamento
  name: string;
  dosage: string;
  frequency: string;
  type: string; // "Cardiológico", "Articular", "Antibiótico", etc.

  // Fechas
  startDate: string; // ISO 8601
  endDate: string | null; // null = crónico

  // Origen
  prescribedBy: string | null;
  generatedFromEventId: string | null;

  // Estado
  active: boolean;
}

// ============================================================================
// Resumen del mes (calculado dinámicamente)
// ============================================================================
export interface MonthSummary {
  month: string; // "Febrero 2026"
  totalEvents: number;
  eventsByType: Record<DocumentType, number>;
  pendingActions: number;
  completedActions: number;
  activeMedications: number;
}

// ============================================================================
// Cita Médica (Turno)
// ============================================================================
export interface Appointment {
  id: string;
  petId: string;
  userId?: string;
  ownerId?: string;
  petName?: string;
  sourceEventId?: string;
  autoGenerated?: boolean;
  type: "checkup" | "vaccine" | "surgery" | "emergency" | "other";
  title: string;
  date: string; // YYYY-MM-DD o ISO
  time: string; // HH:mm
  veterinarian: string | null;
  clinic: string | null;
  status: "upcoming" | "completed" | "cancelled";
  notes?: string;
  createdAt: string;
}

export interface DocumentExtractionResponse {
  extractedData: ExtractedData;
  processingTimeMs: number;
  model: string;
  tokensUsed: number;
}
