import { useState, useRef } from "react";
import { motion, AnimatePresence } from "motion/react";
import { MaterialIcon } from "./MaterialIcon";
import { usePet } from "../contexts/PetContext";
import { useMedical } from "../contexts/MedicalContext";
import { mockProcessDocument } from "../services/geminiService";
import { MedicalEvent, PendingAction, ActiveMedication } from "../types/medical";

interface DocumentScannerModalProps {
  isOpen: boolean;
  onClose: () => void;
}

type UploadStage = "select" | "processing" | "success" | "error";

export function DocumentScannerModal({
  isOpen,
  onClose,
}: DocumentScannerModalProps) {
  const { activePet } = usePet();
  const { addEvent, addPendingAction, addMedication } = useMedical();
  
  const [uploadStage, setUploadStage] = useState<UploadStage>("select");
  const [fileName, setFileName] = useState<string>("");
  const [processingStatus, setProcessingStatus] = useState<string>("Iniciando...");
  const [extractedType, setExtractedType] = useState<string>("");
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileSelect = () => {
    fileInputRef.current?.click();
  };

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setFileName(file.name);
    setUploadStage("processing");

    try {
      // Paso 1: Análisis OCR
      setProcessingStatus("Analizando documento...");
      
      // Paso 2: Llamar a Gemini (mock por ahora)
      setProcessingStatus("Extrayendo información...");
      const geminiResponse = await mockProcessDocument(file);
      
      // Paso 3: Clasificar documento
      setProcessingStatus("Clasificando tipo de documento...");
      const extracted = geminiResponse.extractedData;
      
      // Mapear tipo a español para mostrar
      const typeMap: Record<string, string> = {
        vaccine: "Vacuna",
        lab_test: "Análisis de Laboratorio",
        xray: "Radiografía",
        echocardiogram: "Ecocardiograma",
        electrocardiogram: "Electrocardiograma",
        surgery: "Cirugía",
        medication: "Medicación",
        checkup: "Control",
        other: "Documento General",
      };
      setExtractedType(typeMap[extracted.documentType] || "Documento");
      
      // Paso 4: Crear evento médico
      setProcessingStatus("Creando evento médico...");
      
      // Crear URL temporal para la preview (en producción será Supabase Storage URL)
      const documentUrl = URL.createObjectURL(file);
      
      const newEvent: MedicalEvent = {
        id: `evt_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        petId: activePet.id,
        documentUrl,
        documentPreviewUrl: documentUrl,
        fileName: file.name,
        fileType: file.type.startsWith("image/") ? "image" : "pdf",
        status: "completed",
        extractedData: extracted,
        ocrProcessed: true,
        aiProcessed: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        relatedEventIds: [],
        aiSuggestedRelation: null,
      };
      
      addEvent(newEvent);
      
      // Paso 5: Generar pendientes si hay próxima cita
      if (extracted.nextAppointmentDate) {
        setProcessingStatus("Generando recordatorios...");
        
        const pendingAction: PendingAction = {
          id: `pnd_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
          petId: activePet.id,
          type: extracted.documentType === "vaccine" ? "vaccine_due" : "follow_up",
          title: extracted.nextAppointmentReason || "Próxima cita",
          subtitle: `Programado para ${new Date(extracted.nextAppointmentDate).toLocaleDateString("es-ES", { day: "numeric", month: "long", year: "numeric" })}`,
          dueDate: extracted.nextAppointmentDate,
          createdAt: new Date().toISOString(),
          generatedFromEventId: newEvent.id,
          autoGenerated: true,
          completed: false,
          completedAt: null,
          reminderEnabled: true,
          reminderDaysBefore: 7,
        };
        
        addPendingAction(pendingAction);
      }
      
      // Paso 6: Agregar medicaciones si existen
      if (extracted.medications.length > 0) {
        setProcessingStatus("Agregando medicaciones...");
        
        for (const med of extracted.medications) {
          const activeMed: ActiveMedication = {
            id: `med_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
            petId: activePet.id,
            name: med.name,
            dosage: med.dosage || "Según indicación",
            frequency: med.frequency || "Según indicación",
            type: extracted.documentType === "surgery" ? "Post-quirúrgico" : "Tratamiento",
            startDate: new Date().toISOString(),
            endDate: med.duration && med.duration !== "Crónico" ? new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString() : null,
            prescribedBy: extracted.provider || null,
            generatedFromEventId: newEvent.id,
            active: true,
          };
          
          addMedication(activeMed);
        }
      }
      
      setProcessingStatus("¡Completado!");
      setUploadStage("success");
      
    } catch (error) {
      console.error("Error processing document:", error);
      setUploadStage("error");
      setProcessingStatus("Error al procesar documento");
    }
  };

  const handleClose = () => {
    onClose();
    // Reset after animation
    setTimeout(() => {
      setUploadStage("select");
      setFileName("");
      setProcessingStatus("Iniciando...");
      setExtractedType("");
    }, 300);
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={handleClose}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50"
          />

          {/* Modal */}
          <motion.div
            initial={{ opacity: 0, y: "100%" }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: "100%" }}
            transition={{ type: "spring", damping: 30, stiffness: 300 }}
            className="fixed inset-x-0 bottom-0 z-50 bg-white dark:bg-slate-900 rounded-t-3xl shadow-2xl max-h-[85vh] overflow-hidden flex flex-col"
          >
            {/* Handle */}
            <div className="flex justify-center pt-3 pb-2">
              <div className="w-12 h-1.5 bg-slate-300 dark:bg-slate-700 rounded-full" />
            </div>

            {/* Hidden File Input */}
            <input
              ref={fileInputRef}
              type="file"
              accept="image/*,.pdf"
              onChange={handleFileChange}
              className="hidden"
            />

            {/* Content */}
            <div className="flex-1 overflow-y-auto">
              {/* SELECT TYPE STAGE */}
              {uploadStage === "select" && (
                <div className="p-6">
                  <div className="flex items-center justify-between mb-6">
                    <h2 className="text-2xl font-black text-slate-900 dark:text-white">
                      Agregar Documento
                    </h2>
                    <button
                      onClick={handleClose}
                      className="size-10 rounded-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors"
                    >
                      <MaterialIcon name="close" className="text-xl" />
                    </button>
                  </div>

                  {/* Info sobre procesamiento IA */}
                  <div className="mb-6 p-4 bg-[#2b7cee]/10 border border-[#2b7cee]/20 rounded-2xl">
                    <div className="flex items-start gap-3">
                      <MaterialIcon name="auto_awesome" className="text-[#2b7cee] text-xl mt-0.5" />
                      <div>
                        <p className="text-sm font-bold text-slate-900 dark:text-white mb-1">
                          Procesamiento inteligente automático
                        </p>
                        <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
                          PESSY analizará el documento, extraerá información relevante y generará eventos automáticamente.
                        </p>
                      </div>
                    </div>
                  </div>

                  {/* Two Simple Options */}
                  <div className="space-y-3">
                    {/* Scan with Camera */}
                    <button
                      onClick={handleFileSelect}
                      className="w-full p-5 rounded-2xl bg-[#2b7cee] hover:bg-[#5a8aff] active:scale-95 transition-all flex items-center gap-4"
                    >
                      <div className="size-14 rounded-xl bg-white/20 flex items-center justify-center shrink-0">
                        <MaterialIcon name="photo_camera" className="text-white text-3xl" />
                      </div>
                      <div className="flex-1 text-left">
                        <h3 className="font-black text-white text-lg mb-0.5">
                          Escanear con Cámara
                        </h3>
                        <p className="text-sm text-white/80">
                          Tomar foto del documento
                        </p>
                      </div>
                      <MaterialIcon name="chevron_right" className="text-white/80 text-2xl" />
                    </button>

                    {/* Upload from Files */}
                    <button
                      onClick={handleFileSelect}
                      className="w-full p-5 rounded-2xl bg-white dark:bg-slate-800 border-2 border-slate-200 dark:border-slate-700 hover:border-[#2b7cee] dark:hover:border-[#2b7cee] active:scale-95 transition-all flex items-center gap-4"
                    >
                      <div className="size-14 rounded-xl bg-slate-100 dark:bg-slate-700 flex items-center justify-center shrink-0">
                        <MaterialIcon name="upload_file" className="text-slate-700 dark:text-slate-300 text-3xl" />
                      </div>
                      <div className="flex-1 text-left">
                        <h3 className="font-black text-slate-900 dark:text-white text-lg mb-0.5">
                          Seleccionar Archivo
                        </h3>
                        <p className="text-sm text-slate-600 dark:text-slate-400">
                          Desde galería o archivos
                        </p>
                      </div>
                      <MaterialIcon name="chevron_right" className="text-slate-400 text-2xl" />
                    </button>
                  </div>
                </div>
              )}

              {/* PROCESSING STAGE */}
              {uploadStage === "processing" && (
                <div className="p-6 flex flex-col items-center justify-center min-h-[400px]">
                  <motion.div
                    animate={{ rotate: 360 }}
                    transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
                    className="size-24 rounded-full bg-gradient-to-br from-[#2b7cee] to-purple-500 flex items-center justify-center mb-6 relative"
                  >
                    <div className="absolute inset-2 rounded-full bg-white dark:bg-slate-900 flex items-center justify-center">
                      <MaterialIcon name="auto_awesome" className="text-[#2b7cee] text-4xl" />
                    </div>
                  </motion.div>
                  <h3 className="text-xl font-black text-slate-900 dark:text-white mb-2">
                    {processingStatus}
                  </h3>
                  <p className="text-sm text-slate-500 dark:text-slate-400 text-center max-w-xs mb-2">
                    {fileName}
                  </p>
                  <div className="flex gap-2 mt-4">
                    {["OCR", "IA", "Guardando"].map((step, idx) => (
                      <motion.div
                        key={step}
                        initial={{ opacity: 0.3 }}
                        animate={{ opacity: 1 }}
                        transition={{ delay: idx * 0.3, duration: 0.5, repeat: Infinity }}
                        className="px-3 py-1.5 rounded-full bg-[#2b7cee]/10 text-[#2b7cee] text-xs font-bold"
                      >
                        {step}
                      </motion.div>
                    ))}
                  </div>
                </div>
              )}

              {/* SUCCESS STAGE */}
              {uploadStage === "success" && (
                <div className="p-6 flex flex-col items-center justify-center min-h-[400px]">
                  <motion.div
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ type: "spring", damping: 15 }}
                    className="size-24 rounded-full bg-emerald-500 flex items-center justify-center mb-6"
                  >
                    <MaterialIcon name="check" className="text-white text-5xl" />
                  </motion.div>
                  <h3 className="text-xl font-black text-slate-900 dark:text-white mb-2">
                    ¡Documento procesado!
                  </h3>
                  <p className="text-sm text-slate-500 dark:text-slate-400 text-center max-w-xs mb-1">
                    {fileName}
                  </p>
                  <div className="px-4 py-2 rounded-full bg-[#2b7cee]/10 mb-6">
                    <p className="text-xs font-bold text-[#2b7cee]">
                      Tipo detectado: {extractedType}
                    </p>
                  </div>
                  <button
                    onClick={handleClose}
                    className="px-8 py-3 rounded-xl bg-[#2b7cee] text-white font-bold hover:bg-[#5a8aff] transition-colors shadow-lg shadow-[#2b7cee]/30"
                  >
                    Ver en Timeline
                  </button>
                </div>
              )}

              {/* ERROR STAGE */}
              {uploadStage === "error" && (
                <div className="p-6 flex flex-col items-center justify-center min-h-[400px]">
                  <div className="size-24 rounded-full bg-red-500 flex items-center justify-center mb-6">
                    <MaterialIcon name="error" className="text-white text-5xl" />
                  </div>
                  <h3 className="text-xl font-black text-slate-900 dark:text-white mb-2">
                    Error al procesar
                  </h3>
                  <p className="text-sm text-slate-500 dark:text-slate-400 text-center max-w-xs mb-6">
                    No pudimos procesar el documento. Intenta nuevamente.
                  </p>
                  <button
                    onClick={() => setUploadStage("select")}
                    className="px-8 py-3 rounded-xl bg-slate-900 dark:bg-slate-800 text-white font-bold hover:bg-black dark:hover:bg-slate-700 transition-colors"
                  >
                    Intentar de nuevo
                  </button>
                </div>
              )}
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}