import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import "@testing-library/jest-dom/vitest";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";

const mockGetDoc = vi.fn();
const mockSetDoc = vi.fn();
const mockDoc = vi.fn((...segments: string[]) => segments.join("/"));
const mockAddPoints = vi.fn((amount: number) => amount);
const mockGetActiveMedicationsByPetId = vi.fn();
const mockUpdateMedication = vi.fn();

vi.mock("firebase/firestore", () => ({
  doc: (...args: unknown[]) => mockDoc(...(args as string[])),
  getDoc: (...args: unknown[]) => mockGetDoc(...args),
  setDoc: (...args: unknown[]) => mockSetDoc(...args),
}));

vi.mock("../../../lib/firebase", () => ({
  db: {},
}));

vi.mock("../../contexts/AuthContext", () => ({
  useAuth: () => ({
    user: { uid: "user-123", email: "thor@example.com" },
  }),
}));

vi.mock("../../contexts/MedicalContext", () => ({
  useMedical: () => ({
    getActiveMedicationsByPetId: mockGetActiveMedicationsByPetId,
    updateMedication: mockUpdateMedication,
  }),
}));

vi.mock("../../utils/gamification", () => ({
  addPoints: (amount: number) => mockAddPoints(amount),
}));

import PessyDailyCheckin from "../home/PessyDailyCheckin";
import PessyTip from "../home/PessyTip";
import { CorkMascot } from "../shared/CorkMascot";

describe("Home cards regression", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockGetActiveMedicationsByPetId.mockReturnValue([]);
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it("hides daily checkin when today's checkin already exists", async () => {
    mockGetDoc.mockResolvedValue({ exists: () => true });

    const { container } = render(
      <PessyDailyCheckin
        petName="Thor"
        petId="pet-1"
        species="dog"
        medications={[{ name: "Pimobendan", dosage: "3/4 comprimido" }]}
        nextAppointment={null}
        pendingActions={[]}
      />
    );

    await waitFor(() => {
      expect(mockGetDoc).toHaveBeenCalled();
    });

    expect(container).toBeEmptyDOMElement();
  });

  it("saves medication response and hides the card for the day after marking it", async () => {
    mockGetDoc.mockResolvedValue({ exists: () => false });
    mockSetDoc.mockResolvedValue(undefined);
    mockGetActiveMedicationsByPetId.mockReturnValue([
      {
        id: "med-1",
        active: true,
        name: "Pimobendan",
        frequency: "cada 12 horas",
      },
    ]);

    const { container } = render(
      <PessyDailyCheckin
        petName="Thor"
        petId="pet-1"
        species="dog"
        medications={[{ name: "Pimobendan", dosage: "3/4 comprimido", frequency: "cada 12 horas" }]}
        nextAppointment={null}
        pendingActions={[]}
      />
    );

    await screen.findByText("¿Ya tomó Pimobendan hoy?");
    fireEvent.click(screen.getByRole("button", { name: /Responder/i }));
    fireEvent.click(screen.getByRole("button", { name: /Sí, ya la tomó/i }));

    await waitFor(() => {
      expect(mockSetDoc).toHaveBeenCalled();
      expect(mockAddPoints).toHaveBeenCalledWith(20);
    });

    expect(mockUpdateMedication).toHaveBeenCalledWith(
      "med-1",
      expect.objectContaining({
        lastDoseAt: expect.any(String),
      })
    );

    await new Promise((resolve) => setTimeout(resolve, 2400));

    await waitFor(() => {
      expect(container).toBeEmptyDOMElement();
    });
  }, 8000);

  it("surfaces pending vaccine checkins from real pending actions", async () => {
    mockGetDoc.mockResolvedValue({ exists: () => false });
    mockSetDoc.mockResolvedValue(undefined);

    render(
      <PessyDailyCheckin
        petName="Thor"
        petId="pet-1"
        species="dog"
        medications={[]}
        nextAppointment={null}
        pendingActions={[{
          id: "pending-1",
          petId: "pet-1",
          type: "vaccine_due",
          title: "Refuerzo anual",
          subtitle: "Refuerzo quintupla",
          dueDate: "2026-04-02T10:00:00.000Z",
          createdAt: "2026-03-29T10:00:00.000Z",
          generatedFromEventId: null,
          autoGenerated: true,
          completed: false,
          completedAt: null,
          reminderEnabled: true,
          reminderDaysBefore: 2,
        }]}
      />
    );

    await screen.findByText("Vacuna pendiente para Thor");
    fireEvent.click(screen.getByRole("button", { name: /Responder/i }));
    fireEvent.click(screen.getByRole("button", { name: /Bien/ }));

    await waitFor(() => {
      expect(mockSetDoc).toHaveBeenCalled();
    });

    expect(mockSetDoc.mock.calls.at(-1)?.[1]).toMatchObject({
      kind: "pending",
      pendingActionId: "pending-1",
      pendingActionType: "vaccine_due",
      mood: "bien",
    });
  });

  it("syncs the canonical medication state when the home check-in confirms a dose", async () => {
    mockGetDoc.mockResolvedValue({ exists: () => false });
    mockSetDoc.mockResolvedValue(undefined);
    mockGetActiveMedicationsByPetId.mockReturnValue([
      {
        id: "med-1",
        active: true,
        name: "Pimobendan",
        frequency: "cada 12 horas",
      },
    ]);

    render(
      <PessyDailyCheckin
        petName="Thor"
        petId="pet-1"
        species="dog"
        medications={[{ name: "Pimobendan", dosage: "3/4 comprimido", frequency: "cada 12 horas" }]}
        nextAppointment={null}
        pendingActions={[]}
      />
    );

    await screen.findByText("¿Ya tomó Pimobendan hoy?");
    fireEvent.click(screen.getByRole("button", { name: /Responder/i }));
    fireEvent.click(screen.getByRole("button", { name: /Sí, ya la tomó/i }));

    await waitFor(() => {
      expect(mockUpdateMedication).toHaveBeenCalledWith(
        "med-1",
        expect.objectContaining({
          lastDoseAt: expect.any(String),
          nextDoseAt: expect.any(String),
        })
      );
    });
  });

  it("renders CTA and dismiss actions for non-mission tips", () => {
    const onAction = vi.fn();
    const onDismiss = vi.fn();

    render(
      <PessyTip
        icon="kitchen"
        color="orange"
        title="Chequeo de cocina y basura"
        description="Revisar basura y cocina"
        actionLabel="Ya revisé"
        onAction={onAction}
        dismissLabel="Ocultar hoy"
        onDismiss={onDismiss}
      />
    );

    fireEvent.click(screen.getByRole("button", { name: "Ya revisé" }));
    fireEvent.click(screen.getByRole("button", { name: "Ocultar hoy" }));

    expect(onAction).toHaveBeenCalledTimes(1);
    expect(onDismiss).toHaveBeenCalledTimes(1);
  });

  it("uses the web Cork mascot with the purple collar accent", () => {
    const { container } = render(<CorkMascot size={64} />);
    const svg = container.querySelector("svg");
    expect(svg).toHaveAttribute("viewBox", "0 0 140 170");
    expect(container.querySelector('path[stroke="#5048CA"]')).not.toBeNull();
    expect(container.querySelector('circle[fill="#5048CA"]')).not.toBeNull();
  });
});
