import { createContext, useContext, useState, ReactNode, useEffect } from "react";
import { db } from "../../lib/firebase";
import { collection, query, where, onSnapshot, addDoc, updateDoc, deleteDoc, doc, setDoc } from "firebase/firestore";
import { usePet } from "./PetContext";
import { useAuth } from "./AuthContext";
import {
  MedicalEvent,
  PendingAction,
  ActiveMedication,
  MonthSummary,
  DocumentType,
  Appointment,
} from "../types/medical";

interface MedicalContextType {
  events: MedicalEvent[];
  addEvent: (event: MedicalEvent) => Promise<void>;
  updateEvent: (id: string, updates: Partial<MedicalEvent>) => Promise<void>;
  getEventsByPetId: (petId: string) => MedicalEvent[];

  pendingActions: PendingAction[];
  addPendingAction: (action: PendingAction) => Promise<void>;
  completePendingAction: (id: string) => Promise<void>;
  getPendingActionsByPetId: (petId: string) => PendingAction[];

  activeMedications: ActiveMedication[];
  addMedication: (medication: ActiveMedication) => Promise<void>;
  deactivateMedication: (id: string) => Promise<void>;
  getActiveMedicationsByPetId: (petId: string) => ActiveMedication[];

  getMonthSummary: (petId: string, month: Date) => MonthSummary;
  saveVerifiedReport: (report: any) => Promise<string>;

  appointments: Appointment[];
  addAppointment: (appointment: Appointment) => Promise<void>;
  updateAppointment: (id: string, updates: Partial<Appointment>) => Promise<void>;
  getAppointmentsByPetId: (petId: string) => Appointment[];
}

const MedicalContext = createContext<MedicalContextType | undefined>(undefined);

export function MedicalProvider({ children }: { children: ReactNode }) {
  const { activePet } = usePet();
  const { user } = useAuth();
  const [events, setEvents] = useState<MedicalEvent[]>([]);
  const [pendingActions, setPendingActions] = useState<PendingAction[]>([]);
  const [activeMedications, setActiveMedications] = useState<ActiveMedication[]>([]);
  const [appointments, setAppointments] = useState<Appointment[]>([]);

  const mapDocTypeToAppointmentType = (docType: DocumentType): Appointment["type"] => {
    if (docType === "vaccine") return "vaccine";
    if (docType === "surgery") return "surgery";
    if (docType === "checkup") return "checkup";
    return "other";
  };

  const toDateAndTime = (isoDate: string) => {
    const parsed = new Date(isoDate);
    if (Number.isNaN(parsed.getTime())) return null;
    const yyyy = parsed.getFullYear();
    const mm = String(parsed.getMonth() + 1).padStart(2, "0");
    const dd = String(parsed.getDate()).padStart(2, "0");
    const hh = String(parsed.getHours()).padStart(2, "0");
    const min = String(parsed.getMinutes()).padStart(2, "0");
    const date = `${yyyy}-${mm}-${dd}`;
    const time = `${hh}:${min}`;
    return { date, time };
  };

  const syncAutoAppointmentFromEvent = async (event: MedicalEvent) => {
    const autoAppointmentRef = doc(db, "appointments", `auto_${event.id}`);
    const nextAppointmentDate = event.extractedData?.nextAppointmentDate;

    if (!nextAppointmentDate) {
      await deleteDoc(autoAppointmentRef).catch(() => undefined);
      return;
    }

    const parsed = toDateAndTime(nextAppointmentDate);
    if (!parsed) return;

    await setDoc(autoAppointmentRef, {
      petId: event.petId,
      userId: event.userId || user?.uid,
      petName: activePet?.id === event.petId ? activePet.name : undefined,
      sourceEventId: event.id,
      autoGenerated: true,
      type: mapDocTypeToAppointmentType(event.extractedData.documentType),
      title: event.extractedData.nextAppointmentReason || `Seguimiento de ${event.title}`,
      date: parsed.date,
      time: parsed.time,
      veterinarian: event.extractedData.provider || null,
      clinic: event.extractedData.provider || null,
      status: "upcoming",
      notes: `Generado desde historial: ${event.title}`,
      createdAt: event.createdAt || new Date().toISOString(),
    }, { merge: true });
  };

  // 1. Sync Events
  useEffect(() => {
    if (!activePet) {
      setEvents([]);
      return;
    }
    const q = query(collection(db, "medical_events"), where("petId", "==", activePet.id));
    return onSnapshot(q, (snapshot) => {
      setEvents(snapshot.docs.map(d => ({ id: d.id, ...d.data() } as MedicalEvent)));
    });
  }, [activePet]);

  // 2. Sync Pending Actions
  useEffect(() => {
    if (!activePet) {
      setPendingActions([]);
      return;
    }
    const q = query(collection(db, "pending_actions"), where("petId", "==", activePet.id));
    return onSnapshot(q, (snapshot) => {
      setPendingActions(snapshot.docs.map(d => ({ id: d.id, ...d.data() } as PendingAction)));
    });
  }, [activePet]);

  // 3. Sync Medications
  useEffect(() => {
    if (!activePet) {
      setActiveMedications([]);
      return;
    }
    const q = query(collection(db, "medications"), where("petId", "==", activePet.id));
    return onSnapshot(q, (snapshot) => {
      setActiveMedications(snapshot.docs.map(d => ({ id: d.id, ...d.data() } as ActiveMedication)));
    });
  }, [activePet]);

  // 4. Sync Appointments
  useEffect(() => {
    if (!activePet) {
      setAppointments([]);
      return;
    }
    const q = query(collection(db, "appointments"), where("petId", "==", activePet.id));
    return onSnapshot(q, (snapshot) => {
      setAppointments(snapshot.docs.map(d => ({ id: d.id, ...d.data() } as Appointment)));
    });
  }, [activePet]);

  const addEvent = async (event: MedicalEvent) => {
    const { id, ...data } = event;
    const docRef = id ? doc(db, "medical_events", id) : doc(collection(db, "medical_events"));
    const payload = {
      ...data,
      userId: data.userId || user?.uid,
    };
    await setDoc(docRef, payload);
    await syncAutoAppointmentFromEvent({ ...event, userId: payload.userId });
  };

  const updateEvent = async (id: string, updates: Partial<MedicalEvent>) => {
    const ref = doc(db, "medical_events", id);
    await updateDoc(ref, updates);

    const current = events.find((e) => e.id === id);
    if (!current) return;

    const mergedExtractedData = updates.extractedData
      ? { ...current.extractedData, ...updates.extractedData }
      : current.extractedData;

    const mergedEvent: MedicalEvent = {
      ...current,
      ...updates,
      extractedData: mergedExtractedData,
    };

    await syncAutoAppointmentFromEvent(mergedEvent);
  };

  const getEventsByPetId = (petId: string) => {
    return events.filter(e => e.petId === petId).sort((a, b) => {
      // Ordenar por fecha del documento (eventDate), si no existe usar createdAt (fecha de escaneo)
      const dateA = a.extractedData?.eventDate || a.createdAt;
      const dateB = b.extractedData?.eventDate || b.createdAt;
      return new Date(dateB).getTime() - new Date(dateA).getTime();
    });
  };

  const addPendingAction = async (action: PendingAction) => {
    const { id, ...data } = action;
    const docRef = id ? doc(db, "pending_actions", id) : doc(collection(db, "pending_actions"));
    await setDoc(docRef, {
      ...data,
      userId: data.userId || user?.uid,
    });
  };

  const completePendingAction = async (id: string) => {
    const ref = doc(db, "pending_actions", id);
    await updateDoc(ref, { completed: true, completedAt: new Date().toISOString() });
  };

  const getPendingActionsByPetId = (petId: string) => {
    return pendingActions.filter(a => a.petId === petId && !a.completed);
  };

  const addMedication = async (medication: ActiveMedication) => {
    const { id, ...data } = medication;
    const docRef = id ? doc(db, "medications", id) : doc(collection(db, "medications"));
    await setDoc(docRef, {
      ...data,
      userId: data.userId || user?.uid,
    });
  };

  const deactivateMedication = async (id: string) => {
    const ref = doc(db, "medications", id);
    await updateDoc(ref, { active: false });
  };

  const getActiveMedicationsByPetId = (petId: string) => {
    return activeMedications.filter(m => m.petId === petId && m.active);
  };

  const getMonthSummary = (petId: string, month: Date): MonthSummary => {
    const startOfMonth = new Date(month.getFullYear(), month.getMonth(), 1);
    const endOfMonth = new Date(month.getFullYear(), month.getMonth() + 1, 0);

    const petEvents = events.filter((event) => {
      const eventDate = new Date(event.extractedData?.eventDate || event.createdAt);
      return event.petId === petId && eventDate >= startOfMonth && eventDate <= endOfMonth;
    });

    const eventsByType: Record<DocumentType, number> = {
      vaccine: 0, lab_test: 0, xray: 0, echocardiogram: 0, electrocardiogram: 0,
      surgery: 0, medication: 0, checkup: 0, other: 0,
    };

    petEvents.forEach((event) => {
      const type = event.extractedData.documentType;
      eventsByType[type] = (eventsByType[type] || 0) + 1;
    });

    const petPendingActions = pendingActions.filter((action) => action.petId === petId);
    const completedThisMonth = petPendingActions.filter((action) => {
      if (!action.completedAt) return false;
      const completedDate = new Date(action.completedAt);
      return completedDate >= startOfMonth && completedDate <= endOfMonth;
    });

    const monthName = month.toLocaleDateString("es-ES", { month: "long" });

    return {
      month: monthName.charAt(0).toUpperCase() + monthName.slice(1),
      totalEvents: petEvents.length,
      eventsByType,
      pendingActions: getPendingActionsByPetId(petId).length,
      completedActions: completedThisMonth.length,
      activeMedications: getActiveMedicationsByPetId(petId).length,
    };
  };

  const saveVerifiedReport = async (report: any) => {
    const docRef = await addDoc(collection(db, "verified_reports"), {
      ...report,
      generatedAt: new Date().toISOString(),
    });
    return docRef.id;
  };

  const addAppointment = async (appointment: Appointment) => {
    const { id, ...data } = appointment;
    const docRef = id ? doc(db, "appointments", id) : doc(collection(db, "appointments"));
    await setDoc(docRef, {
      ...data,
      userId: data.userId || user?.uid,
    });
  };

  const updateAppointment = async (id: string, updates: Partial<Appointment>) => {
    const ref = doc(db, "appointments", id);
    await updateDoc(ref, updates);
  };

  const getAppointmentsByPetId = (petId: string) => {
    const toTimestamp = (appointment: Appointment) => {
      const withTime = appointment.time
        ? `${appointment.date}T${appointment.time}:00`
        : `${appointment.date}T00:00:00`;
      const parsed = new Date(withTime);
      if (!Number.isNaN(parsed.getTime())) return parsed.getTime();
      return new Date(appointment.createdAt || 0).getTime();
    };

    return appointments
      .filter(a => a.petId === petId)
      .sort((a, b) => toTimestamp(a) - toTimestamp(b));
  };

  return (
    <MedicalContext.Provider
      value={{
        events, addEvent, updateEvent, getEventsByPetId,
        pendingActions, addPendingAction, completePendingAction, getPendingActionsByPetId,
        activeMedications, addMedication, deactivateMedication, getActiveMedicationsByPetId,
        getMonthSummary, saveVerifiedReport,
        appointments, addAppointment, updateAppointment, getAppointmentsByPetId,
      }}
    >
      {children}
    </MedicalContext.Provider>
  );
}

export function useMedical() {
  const context = useContext(MedicalContext);
  if (!context) throw new Error("useMedical must be used within MedicalProvider");
  return context;
}
