import type { MedicalEvent, Appointment } from "../types/medical";
import { parseDateSafe } from "./dateUtils";

export const normalizeForHint = (value?: string | null) =>
  (value || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");

export const hasMailSyncHint = (value?: string | null) => {
  const text = normalizeForHint(value);
  if (!text) return false;
  return /(correo|mail|gmail|sincroniz|sync)/.test(text);
};

export const normalizeMedicationKey = (value?: string | null) =>
  (value || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();

export const extractTimeFromText = (value?: string | null): string | null => {
  const text = (value || "").trim();
  const match = text.match(/\b([01]?\d|2[0-3]):([0-5]\d)\b/);
  if (!match) return null;
  return `${match[1].padStart(2, "0")}:${match[2]}`;
};

export const hasAppointmentLanguage = (value?: string | null): boolean => {
  const text = normalizeForHint(value);
  if (!text) return false;
  return /(turno|consulta|control|recordatorio|confirmacion|confirmado|agendad|programad|reprogramad|cancelad|cita)/.test(text);
};

export const extractSpecialtyFromText = (value?: string | null): string | null => {
  const text = (value || "").trim();
  const match = text.match(/\b(?:consulta|control|turno)\s+([a-záéíóúñ]+(?:\s+[a-záéíóúñ]+){0,3})/i);
  return match?.[1]?.trim() || null;
};

export const deriveAppointmentCandidateFromEvent = (event: MedicalEvent): Appointment | null => {
  const extracted = event.extractedData || {};
  const sourceText = [
    extracted.sourceSubject,
    extracted.suggestedTitle,
    extracted.observations,
    extracted.aiGeneratedSummary,
    event.title,
  ]
    .filter(Boolean)
    .join(" · ");
  const detectedRows = Array.isArray(extracted.detectedAppointments) ? extracted.detectedAppointments : [];
  const detected = (detectedRows[0] || {}) as Record<string, unknown>;
  const rawDate =
    (typeof detected.date === "string" ? detected.date : "") ||
    extracted.nextAppointmentDate ||
    extracted.eventDate ||
    "";
  const parsedDate = parseDateSafe(rawDate);
  if (!parsedDate) return null;

  const endOfYesterday = new Date();
  endOfYesterday.setHours(0, 0, 0, 0);
  if (parsedDate.getTime() < endOfYesterday.getTime()) return null;

  const explicitAppointment =
    extracted.documentType === "appointment" ||
    detectedRows.length > 0 ||
    Boolean(extracted.appointmentTime);
  if (!explicitAppointment && !hasAppointmentLanguage(sourceText)) return null;

  const title =
    (typeof detected.title === "string" ? detected.title.trim() : "") ||
    extracted.suggestedTitle ||
    event.title ||
    "Turno veterinario";
  const time =
    extracted.appointmentTime ||
    (typeof detected.time === "string" ? detected.time : "") ||
    extractTimeFromText(sourceText) ||
    "";
  const veterinarian =
    extracted.provider ||
    (typeof detected.provider === "string" ? detected.provider : "") ||
    null;
  const clinic =
    extracted.clinic ||
    (typeof detected.clinic === "string" ? detected.clinic : "") ||
    null;
  const specialty =
    (typeof detected.specialty === "string" ? detected.specialty.trim() : "") ||
    extractSpecialtyFromText(sourceText) ||
    "";

  if (!explicitAppointment && !time && !veterinarian && !clinic && !specialty) return null;

  const normalizedTitle = title.trim();
  return {
    id: `auto_${event.id}`,
    petId: event.petId,
    userId: event.userId,
    ownerId: event.userId,
    sourceEventId: event.id,
    sourceSuggestionKey: `${event.id}|${rawDate}|${time}|${normalizedTitle.toLowerCase()}`,
    autoGenerated: true,
    type: extracted.documentType === "vaccine" ? "vaccine" : "checkup",
    title: normalizedTitle,
    date: rawDate,
    time,
    veterinarian,
    clinic,
    status: /cancelad/i.test(sourceText) ? "cancelled" : "upcoming",
    notes: sourceText.slice(0, 500),
    createdAt: event.createdAt,
  };
};
